name: Graphic Regressions CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  no-scheduling:
    runs-on: ubuntu-latest
    steps:
      - name: Dont schedule all jobs
        run: sleep 10

  gfx-regressions:
    needs: no-scheduling
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    env:
      VFLAGS: -cc tcc
      DISPLAY: :99
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - uses: openrndr/setup-opengl@v1.1
      - uses: actions/checkout@v2
        with:
          path: greg

      - name: Setup dependencies
        run: |
          # xvfb: xvfb (installed by openrndr/setup-opengl@v1.1)
          # x11-utils: xwininfo -root -int -tree
          # x11-apps: xwd
          # openimageio-tools: idiff
          # mesa-common-dev libxcursor-dev libxi-dev: V deps for headless rendering
          # freeglut3-dev: fix graphic apps compilation with tcc
          sudo apt-get install imagemagick openimageio-tools mesa-common-dev libxcursor-dev libxi-dev freeglut3-dev x11-apps x11-utils
          wget https://raw.githubusercontent.com/tremby/imgur.sh/c98345d/imgur.sh
          chmod +x ./imgur.sh

      - name: Build local v
        run: make -j4

      - name: Build test binaries
        run: |
          mkdir -p /tmp/examples/gg/
          sudo /usr/bin/Xvfb -screen 0 1000x600x24 &
          ./v -o examples/gg/rectangles examples/gg/rectangles.v
          sudo examples/gg/rectangles &
          sleep 1
          sudo xwd -root -silent -out /tmp/examples/gg/rectangles.xwd
          sudo convert xwd:/tmp/examples/gg/rectangles.xwd png:/tmp/examples/gg/rectangles.png
          killall rectangles

      - name: Compare
        id: compare
        continue-on-error: true
        run: |
          sudo idiff greg/examples/gg/rectangles.png /tmp/examples/gg/rectangles.png

      - name: Upload regression to imgur
        if: steps.compare.outcome != 'success'
        run: |
          ./imgur.sh /tmp/examples/gg/rectangles.png
          exit 1
